version: "3.8"

services:
  nextjs-app:
    image: ghcr.io/110kanishkamedankara110/nextjsdockertest:latest
    container_name: nextjs-app
    environment:
      - NODE_ENV=production
    restart: unless-stopped
  nextjs-app-2:
    image: ghcr.io/110kanishkamedankara110/nextjstmb:latest
    container_name: nextjs-app-2
    environment:
      - NODE_ENV=production
    restart: unless-stopped
  nginx:
    image: nginx:latest
    container_name: nginx-proxy
    ports:
      - "81:80"
      - "8081:8080"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - nextjs-app
    restart: unless-stopped
