version: "3.8"

services:
  nextjs-app:
    image: ghcr.io/110kanishkamedankara110/110kanishkamedankara110:latest
    container_name: nextjs-app
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    restart: always

  nginx:
    image: nginx:latest
    container_name: nginx-proxy
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - nextjs-app
    restart: always
